module.exports = {
  inputFiles: ['lib/*.ts'],
  mode: 'library',
  out: 'docs',
  plugin: 'typedoc-plugin-markdown',
  readme: 'none',
  gitRevision: 'master',
  exclude: [
    'test/**/*.ts',
    'lib/bloom/*.ts',
    'lib/evm/precompiles/*.ts',
    'lib/evm/eei.ts',
    'lib/evm/interpreter.ts',
    'lib/evm/memory.ts',
    'lib/evm/message.ts',
    'lib/evm/opcodes.ts',
    'lib/evm/opFns.ts',
    'lib/evm/stack.ts',
    'lib/evm/txContext.ts',
    'lib/state/promisified.ts',
  ],
  excludeNotExported: true,
  excludePrivate: true,
  excludeProtected: true,
}
