const c = {}

// Chain constants
c.MAINNET_NETWORK_ID = 1
c.ROPSTEN_NETWORK_ID = 3
c.RINKEBY_NETWORK_ID = 4

c.SUPPORTED_NETWORK_IDS = [
  c.MAINNET_NETWORK_ID,
  c.ROPSTEN_NETWORK_ID,
  c.RINKEBY_NETWORK_ID
]

c.DEFAULT_NETWORK_ID = c.MAINNET_NETWORK_ID

module.exports = c
