const c = {}

// Chain constants
c.MAINNET_NETWORK_ID = 1
c.ROPSTEN_NETWORK_ID = 3
c.RINKEBY_NETWORK_ID = 4

c.SUPPORTED_NETWORK_IDS = [
  c.MAINNET_NETWORK_ID,
  c.ROPSTEN_NETWORK_ID,
  c.RINKEBY_NETWORK_ID
]

c.DEFAULT_NETWORK_ID = c.MAINNET_NETWORK_ID

c.ERROR_LOG_LEVEL = 'error'
c.WARN_LOG_LEVEL = 'warn'
c.INFO_LOG_LEVEL = 'info'
c.DEBUG_LOG_LEVEL = 'debug'

c.SUPPORTED_LOG_LEVELS = [
  c.ERROR_LOG_LEVEL,
  c.WARN_LOG_LEVEL,
  c.INFO_LOG_LEVEL,
  c.DEBUG_LOG_LEVEL
]

c.DEFAULT_LOG_LEVEL = c.INFO_LOG_LEVEL

c.DEFAULT_RPC_PORT = 8545

c.DEFAULT_RPC_ADDR = 'localhost'

module.exports = c
