export const stackDelta: {
  [key: number]: {
    inputs: number
    outputs: number
    name: string
    intermediates: number
    terminating?: boolean
  }
} = {
  0x00: { inputs: 0, outputs: 0, name: 'STOP', intermediates: 0, terminating: true },
  0x01: { inputs: 2, outputs: 1, name: 'ADD', intermediates: 0 },
  0x02: { inputs: 2, outputs: 1, name: 'MUL', intermediates: 0 },
  0x03: { inputs: 2, outputs: 1, name: 'SUB', intermediates: 0 },
  0x04: { inputs: 2, outputs: 1, name: 'DIV', intermediates: 0 },
  0x05: { inputs: 2, outputs: 1, name: 'SDIV', intermediates: 0 },
  0x06: { inputs: 2, outputs: 1, name: 'MOD', intermediates: 0 },
  0x07: { inputs: 2, outputs: 1, name: 'SMOD', intermediates: 0 },
  0x08: { inputs: 3, outputs: 1, name: 'ADDMOD', intermediates: 0 },
  0x09: { inputs: 3, outputs: 1, name: 'MULMOD', intermediates: 0 },
  0x0a: { inputs: 2, outputs: 1, name: 'EXP', intermediates: 0 },
  0x0b: { inputs: 2, outputs: 1, name: 'SIGNEXTEND', intermediates: 0 },
  0x10: { inputs: 2, outputs: 1, name: 'LT', intermediates: 0 },
  0x11: { inputs: 2, outputs: 1, name: 'GT', intermediates: 0 },
  0x12: { inputs: 2, outputs: 1, name: 'SLT', intermediates: 0 },
  0x13: { inputs: 2, outputs: 1, name: 'SGT', intermediates: 0 },
  0x14: { inputs: 2, outputs: 1, name: 'EQ', intermediates: 0 },
  0x15: { inputs: 1, outputs: 1, name: 'ISZERO', intermediates: 0 },
  0x16: { inputs: 2, outputs: 1, name: 'AND', intermediates: 0 },
  0x17: { inputs: 2, outputs: 1, name: 'OR', intermediates: 0 },
  0x18: { inputs: 2, outputs: 1, name: 'XOR', intermediates: 0 },
  0x19: { inputs: 1, outputs: 1, name: 'NOT', intermediates: 0 },
  0x1a: { inputs: 2, outputs: 1, name: 'BYTE', intermediates: 0 },
  0x1b: { inputs: 2, outputs: 1, name: 'SHL', intermediates: 0 },
  0x1c: { inputs: 2, outputs: 1, name: 'SHR', intermediates: 0 },
  0x1d: { inputs: 2, outputs: 1, name: 'SAR', intermediates: 0 },
  0x20: { inputs: 2, outputs: 1, name: 'SHA3', intermediates: 0 },
  0x30: { inputs: 0, outputs: 1, name: 'ADDRESS', intermediates: 0 },
  0x31: { inputs: 1, outputs: 1, name: 'BALANCE', intermediates: 0 },
  0x32: { inputs: 0, outputs: 1, name: 'ORIGIN', intermediates: 0 },
  0x33: { inputs: 0, outputs: 1, name: 'CALLER', intermediates: 0 },
  0x34: { inputs: 0, outputs: 1, name: 'CALLVALUE', intermediates: 0 },
  0x35: { inputs: 1, outputs: 1, name: 'CALLDATALOAD', intermediates: 0 },
  0x36: { inputs: 0, outputs: 1, name: 'CALLDATASIZE', intermediates: 0 },
  0x37: { inputs: 3, outputs: 0, name: 'CALLDATACOPY', intermediates: 0 },
  0x3a: { inputs: 0, outputs: 1, name: 'GASPRICE', intermediates: 0 },
  0x3d: { inputs: 0, outputs: 1, name: 'RETURNDATASIZE', intermediates: 0 },
  0x3e: { inputs: 3, outputs: 0, name: 'RETURNDATACOPY', intermediates: 0 },
  0x40: { inputs: 1, outputs: 1, name: 'BLOCKHASH', intermediates: 0 },
  0x41: { inputs: 0, outputs: 1, name: 'COINBASE', intermediates: 0 },
  0x42: { inputs: 0, outputs: 1, name: 'TIMESTAMP', intermediates: 0 },
  0x43: { inputs: 0, outputs: 1, name: 'NUMBER', intermediates: 0 },
  0x44: { inputs: 0, outputs: 1, name: 'PREVRANDAO', intermediates: 0 },
  0x45: { inputs: 0, outputs: 1, name: 'GASLIMIT', intermediates: 0 },
  0x46: { inputs: 0, outputs: 1, name: 'CHAINID', intermediates: 0 },
  0x47: { inputs: 0, outputs: 1, name: 'SELFBALANCE', intermediates: 0 },
  0x48: { inputs: 0, outputs: 1, name: 'BASEFEE', intermediates: 0 },
  0x49: { inputs: 1, outputs: 1, name: 'BLOBAHASH', intermediates: 0 },
  0x4a: { inputs: 0, outputs: 1, name: 'BLOBBASEFEE', intermediates: 0 },
  0x50: { inputs: 1, outputs: 0, name: 'POP', intermediates: 0 },
  0x51: { inputs: 1, outputs: 1, name: 'MLOAD', intermediates: 0 },
  0x52: { inputs: 2, outputs: 0, name: 'MSTORE', intermediates: 0 },
  0x53: { inputs: 2, outputs: 0, name: 'MSTORE8', intermediates: 0 },
  0x54: { inputs: 1, outputs: 1, name: 'SLOAD', intermediates: 0 },
  0x55: { inputs: 2, outputs: 0, name: 'SSTORE', intermediates: 0 },
  0x59: { inputs: 0, outputs: 1, name: 'MSIZE', intermediates: 0 },
  0x5b: { inputs: 0, outputs: 0, name: 'NOOP', intermediates: 0 },
  0x5c: { inputs: 1, outputs: 1, name: 'TLOAD', intermediates: 0 },
  0x5d: { inputs: 2, outputs: 0, name: 'TSTORE', intermediates: 0 },
  0x5e: { inputs: 3, outputs: 0, name: 'MCOPY', intermediates: 0 },
  0x5f: { inputs: 0, outputs: 1, name: 'PUSH0', intermediates: 0 },
  0x60: { inputs: 0, outputs: 1, name: 'PUSH1', intermediates: 1 },
  0x61: { inputs: 0, outputs: 1, name: 'PUSH2', intermediates: 2 },
  0x62: { inputs: 0, outputs: 1, name: 'PUSH3', intermediates: 3 },
  0x63: { inputs: 0, outputs: 1, name: 'PUSH4', intermediates: 4 },
  0x64: { inputs: 0, outputs: 1, name: 'PUSH5', intermediates: 5 },
  0x65: { inputs: 0, outputs: 1, name: 'PUSH6', intermediates: 6 },
  0x66: { inputs: 0, outputs: 1, name: 'PUSH7', intermediates: 7 },
  0x67: { inputs: 0, outputs: 1, name: 'PUSH8', intermediates: 8 },
  0x68: { inputs: 0, outputs: 1, name: 'PUSH9', intermediates: 9 },
  0x69: { inputs: 0, outputs: 1, name: 'PUSH10', intermediates: 10 },
  0x6a: { inputs: 0, outputs: 1, name: 'PUSH11', intermediates: 11 },
  0x6b: { inputs: 0, outputs: 1, name: 'PUSH12', intermediates: 12 },
  0x6c: { inputs: 0, outputs: 1, name: 'PUSH13', intermediates: 13 },
  0x6d: { inputs: 0, outputs: 1, name: 'PUSH14', intermediates: 14 },
  0x6e: { inputs: 0, outputs: 1, name: 'PUSH15', intermediates: 15 },
  0x6f: { inputs: 0, outputs: 1, name: 'PUSH16', intermediates: 16 },
  0x70: { inputs: 0, outputs: 1, name: 'PUSH17', intermediates: 17 },
  0x71: { inputs: 0, outputs: 1, name: 'PUSH18', intermediates: 18 },
  0x72: { inputs: 0, outputs: 1, name: 'PUSH19', intermediates: 19 },
  0x73: { inputs: 0, outputs: 1, name: 'PUSH20', intermediates: 20 },
  0x74: { inputs: 0, outputs: 1, name: 'PUSH21', intermediates: 21 },
  0x75: { inputs: 0, outputs: 1, name: 'PUSH22', intermediates: 22 },
  0x76: { inputs: 0, outputs: 1, name: 'PUSH23', intermediates: 23 },
  0x77: { inputs: 0, outputs: 1, name: 'PUSH24', intermediates: 24 },
  0x78: { inputs: 0, outputs: 1, name: 'PUSH25', intermediates: 25 },
  0x79: { inputs: 0, outputs: 1, name: 'PUSH26', intermediates: 26 },
  0x7a: { inputs: 0, outputs: 1, name: 'PUSH27', intermediates: 27 },
  0x7b: { inputs: 0, outputs: 1, name: 'PUSH28', intermediates: 28 },
  0x7c: { inputs: 0, outputs: 1, name: 'PUSH29', intermediates: 29 },
  0x7d: { inputs: 0, outputs: 1, name: 'PUSH30', intermediates: 30 },
  0x7e: { inputs: 0, outputs: 1, name: 'PUSH31', intermediates: 31 },
  0x7f: { inputs: 0, outputs: 1, name: 'PUSH32', intermediates: 32 },
  0x80: { inputs: 1, outputs: 2, name: 'DUP1', intermediates: 0 },
  0x81: { inputs: 2, outputs: 3, name: 'DUP2', intermediates: 0 },
  0x82: { inputs: 3, outputs: 4, name: 'DUP3', intermediates: 0 },
  0x83: { inputs: 4, outputs: 5, name: 'DUP4', intermediates: 0 },
  0x84: { inputs: 5, outputs: 6, name: 'DUP5', intermediates: 0 },
  0x85: { inputs: 6, outputs: 7, name: 'DUP6', intermediates: 0 },
  0x86: { inputs: 7, outputs: 8, name: 'DUP7', intermediates: 0 },
  0x87: { inputs: 8, outputs: 9, name: 'DUP8', intermediates: 0 },
  0x88: { inputs: 9, outputs: 10, name: 'DUP9', intermediates: 0 },
  0x89: { inputs: 10, outputs: 11, name: 'DUP10', intermediates: 0 },
  0x8a: { inputs: 11, outputs: 12, name: 'DUP11', intermediates: 0 },
  0x8b: { inputs: 12, outputs: 13, name: 'DUP12', intermediates: 0 },
  0x8c: { inputs: 13, outputs: 14, name: 'DUP13', intermediates: 0 },
  0x8d: { inputs: 14, outputs: 15, name: 'DUP14', intermediates: 0 },
  0x8e: { inputs: 15, outputs: 16, name: 'DUP15', intermediates: 0 },
  0x8f: { inputs: 16, outputs: 17, name: 'DUP16', intermediates: 0 },
  0x90: { inputs: 2, outputs: 2, name: 'SWAP1', intermediates: 0 },
  0x91: { inputs: 3, outputs: 3, name: 'SWAP2', intermediates: 0 },
  0x92: { inputs: 4, outputs: 4, name: 'SWAP3', intermediates: 0 },
  0x93: { inputs: 5, outputs: 5, name: 'SWAP4', intermediates: 0 },
  0x94: { inputs: 6, outputs: 6, name: 'SWAP5', intermediates: 0 },
  0x95: { inputs: 7, outputs: 7, name: 'SWAP6', intermediates: 0 },
  0x96: { inputs: 8, outputs: 8, name: 'SWAP7', intermediates: 0 },
  0x97: { inputs: 9, outputs: 9, name: 'SWAP8', intermediates: 0 },
  0x98: { inputs: 10, outputs: 10, name: 'SWAP9', intermediates: 0 },
  0x99: { inputs: 11, outputs: 11, name: 'SWAP10', intermediates: 0 },
  0x9a: { inputs: 12, outputs: 12, name: 'SWAP11', intermediates: 0 },
  0x9b: { inputs: 13, outputs: 13, name: 'SWAP12', intermediates: 0 },
  0x9c: { inputs: 14, outputs: 14, name: 'SWAP13', intermediates: 0 },
  0x9d: { inputs: 15, outputs: 15, name: 'SWAP14', intermediates: 0 },
  0x9e: { inputs: 16, outputs: 16, name: 'SWAP15', intermediates: 0 },
  0x9f: { inputs: 17, outputs: 17, name: 'SWAP16', intermediates: 0 },
  0xa0: { inputs: 2, outputs: 0, name: 'LOG0', intermediates: 0 },
  0xa1: { inputs: 3, outputs: 0, name: 'LOG1', intermediates: 0 },
  0xa2: { inputs: 4, outputs: 0, name: 'LOG2', intermediates: 0 },
  0xa3: { inputs: 5, outputs: 0, name: 'LOG3', intermediates: 0 },
  0xa4: { inputs: 6, outputs: 0, name: 'LOG4', intermediates: 0 },
  0xd0: { inputs: 1, outputs: 1, name: 'DATALOAD', intermediates: 0 },
  0xd1: { inputs: 0, outputs: 1, name: 'DATALOADN', intermediates: 2 },
  0xd2: { inputs: 0, outputs: 1, name: 'DATASIZE', intermediates: 0 },
  0xd3: { inputs: 3, outputs: 0, name: 'DATACOPY', intermediates: 0 },
  0xe0: { inputs: 0, outputs: 0, name: 'RJUMP', intermediates: 2 },
  0xe1: { inputs: 1, outputs: 0, name: 'RJUMPI', intermediates: 2 },
  0xe2: { inputs: 1, outputs: 0, name: 'RJUMPV', intermediates: 1 },
  0xe3: { inputs: 0, outputs: 0, name: 'CALLF', intermediates: 2 },
  0xe4: { inputs: 0, outputs: 0, name: 'RETF', intermediates: 0, terminating: true },
  0xe5: { inputs: 0, outputs: 0, name: 'JUMPF', intermediates: 2, terminating: true },
  0xe6: { inputs: 0, outputs: 1, name: 'DUPN', intermediates: 1 },
  0xe7: { inputs: 0, outputs: 0, name: 'SWAPN', intermediates: 1 },
  0xe8: { inputs: 0, outputs: 0, name: 'EXCHANGE', intermediates: 1 },
  0xec: { inputs: 4, outputs: 1, name: 'EOFCREATE', intermediates: 1 },
  0xee: { inputs: 2, outputs: 1, name: 'RETURNCONTRACT', intermediates: 1, terminating: true },
  0xf3: { inputs: 2, outputs: 0, name: 'RETURN', intermediates: 0, terminating: true },
  0xf7: { inputs: 1, outputs: 1, name: 'RETURNDATALOAD', intermediates: 0 },
  0xf8: { inputs: 4, outputs: 1, name: 'EXTCALL', intermediates: 0 },
  0xf9: { inputs: 3, outputs: 1, name: 'EXTDELEGATECALL', intermediates: 0 },
  0xfb: { inputs: 3, outputs: 1, name: 'EXTSTATICCALL', intermediates: 0 },
  0xfd: { inputs: 2, outputs: 0, name: 'REVERT', intermediates: 0, terminating: true },
  0xfe: { inputs: 0, outputs: 0, name: 'INVALID', intermediates: 0, terminating: true },
}

/*

// Generated using:

const stackDelta: any = {}

class OpcodeInfo {
  static terminalOpcode(
    instr: string,
    opcode: number,
    inputs: number,
    outputs: number,
    opSize: number
  ) {
    return this.parse(instr, opcode, inputs, outputs, opSize)
  }

  static validOpcode(
    instr: string,
    opcode: number,
    inputs: number,
    outputs: number,
    opSize: number
  ) {
    return this.parse(instr, opcode, inputs, outputs, opSize)
  }
  static unallocatedOpcode(opcode: number) {
    return undefined
  }

  static invalidOpcode(instr: string, opcode: number) {
    return undefined
  }

  static parse(instr: string, opcode: number, inputs: number, outputs: number, opSize: number) {
    const hexStr = '0x' + opcode.toString(16).padStart(2, '0')
    stackDelta[hexStr] = {
      inputs,
      outputs,
      name: instr,
      intermediates: opSize - 1,
    }
  }
}

// This code is from Besu: https://github.com/hyperledger/besu/blob/ac5d03f91d4c9e938ff5b4ba90abae1bb4afa997/evm/src/main/java/org/hyperledger/besu/evm/code/OpcodeInfo.java#L79
const tbl = [
  OpcodeInfo.terminalOpcode('STOP', 0x00, 0, 0, 1),
  OpcodeInfo.validOpcode('ADD', 0x01, 2, 1, 1),
  OpcodeInfo.validOpcode('MUL', 0x02, 2, 1, 1),
  OpcodeInfo.validOpcode('SUB', 0x03, 2, 1, 1),
  OpcodeInfo.validOpcode('DIV', 0x04, 2, 1, 1),
  OpcodeInfo.validOpcode('SDIV', 0x05, 2, 1, 1),
  OpcodeInfo.validOpcode('MOD', 0x06, 2, 1, 1),
  OpcodeInfo.validOpcode('SMOD', 0x07, 2, 1, 1),
  OpcodeInfo.validOpcode('ADDMOD', 0x08, 3, 1, 1),
  OpcodeInfo.validOpcode('MULMOD', 0x09, 3, 1, 1),
  OpcodeInfo.validOpcode('EXP', 0x0a, 2, 1, 1),
  OpcodeInfo.validOpcode('SIGNEXTEND', 0x0b, 2, 1, 1),
  OpcodeInfo.unallocatedOpcode(0x0c),
  OpcodeInfo.unallocatedOpcode(0x0d),
  OpcodeInfo.unallocatedOpcode(0x0e),
  OpcodeInfo.unallocatedOpcode(0x0f),
  OpcodeInfo.validOpcode('LT', 0x10, 2, 1, 1),
  OpcodeInfo.validOpcode('GT', 0x11, 2, 1, 1),
  OpcodeInfo.validOpcode('SLT', 0x12, 2, 1, 1),
  OpcodeInfo.validOpcode('SGT', 0x13, 2, 1, 1),
  OpcodeInfo.validOpcode('EQ', 0x14, 2, 1, 1),
  OpcodeInfo.validOpcode('ISZERO', 0x15, 1, 1, 1),
  OpcodeInfo.validOpcode('AND', 0x16, 2, 1, 1),
  OpcodeInfo.validOpcode('OR', 0x17, 2, 1, 1),
  OpcodeInfo.validOpcode('XOR', 0x18, 2, 1, 1),
  OpcodeInfo.validOpcode('NOT', 0x19, 1, 1, 1),
  OpcodeInfo.validOpcode('BYTE', 0x1a, 2, 1, 1),
  OpcodeInfo.validOpcode('SHL', 0x1b, 2, 1, 1),
  OpcodeInfo.validOpcode('SHR', 0x1c, 2, 1, 1),
  OpcodeInfo.validOpcode('SAR', 0x1d, 2, 1, 1),
  OpcodeInfo.unallocatedOpcode(0x1e),
  OpcodeInfo.unallocatedOpcode(0x1f),
  OpcodeInfo.validOpcode('SHA3', 0x20, 2, 1, 1),
  OpcodeInfo.unallocatedOpcode(0x21),
  OpcodeInfo.unallocatedOpcode(0x22),
  OpcodeInfo.unallocatedOpcode(0x23),
  OpcodeInfo.unallocatedOpcode(0x24),
  OpcodeInfo.unallocatedOpcode(0x25),
  OpcodeInfo.unallocatedOpcode(0x26),
  OpcodeInfo.unallocatedOpcode(0x27),
  OpcodeInfo.unallocatedOpcode(0x28),
  OpcodeInfo.unallocatedOpcode(0x29),
  OpcodeInfo.unallocatedOpcode(0x2a),
  OpcodeInfo.unallocatedOpcode(0x2b),
  OpcodeInfo.unallocatedOpcode(0x2c),
  OpcodeInfo.unallocatedOpcode(0x2d),
  OpcodeInfo.unallocatedOpcode(0x2e),
  OpcodeInfo.unallocatedOpcode(0x2f),
  OpcodeInfo.validOpcode('ADDRESS', 0x30, 0, 1, 1),
  OpcodeInfo.validOpcode('BALANCE', 0x31, 1, 1, 1),
  OpcodeInfo.validOpcode('ORIGIN', 0x32, 0, 1, 1),
  OpcodeInfo.validOpcode('CALLER', 0x33, 0, 1, 1),
  OpcodeInfo.validOpcode('CALLVALUE', 0x34, 0, 1, 1),
  OpcodeInfo.validOpcode('CALLDATALOAD', 0x35, 1, 1, 1),
  OpcodeInfo.validOpcode('CALLDATASIZE', 0x36, 0, 1, 1),
  OpcodeInfo.validOpcode('CALLDATACOPY', 0x37, 3, 0, 1),
  OpcodeInfo.invalidOpcode('CODESIZE', 0x38),
  OpcodeInfo.invalidOpcode('CODECOPY', 0x39),
  OpcodeInfo.validOpcode('GASPRICE', 0x3a, 0, 1, 1),
  OpcodeInfo.invalidOpcode('EXTCODESIZE', 0x3b),
  OpcodeInfo.invalidOpcode('EXTCODECOPY', 0x3c),
  OpcodeInfo.validOpcode('RETURNDATASIZE', 0x3d, 0, 1, 1),
  OpcodeInfo.validOpcode('RETURNDATACOPY', 0x3e, 3, 0, 1),
  OpcodeInfo.invalidOpcode('EXTCODEHASH', 0x3f),
  OpcodeInfo.validOpcode('BLOCKHASH', 0x40, 1, 1, 1),
  OpcodeInfo.validOpcode('COINBASE', 0x41, 0, 1, 1),
  OpcodeInfo.validOpcode('TIMESTAMP', 0x42, 0, 1, 1),
  OpcodeInfo.validOpcode('NUMBER', 0x43, 0, 1, 1),
  OpcodeInfo.validOpcode('PREVRANDAO', 0x44, 0, 1, 1), // was DIFFICULTY
  OpcodeInfo.validOpcode('GASLIMIT', 0x45, 0, 1, 1),
  OpcodeInfo.validOpcode('CHAINID', 0x46, 0, 1, 1),
  OpcodeInfo.validOpcode('SELFBALANCE', 0x47, 0, 1, 1),
  OpcodeInfo.validOpcode('BASEFEE', 0x48, 0, 1, 1),
  OpcodeInfo.validOpcode('BLOBAHASH', 0x49, 1, 1, 1),
  OpcodeInfo.validOpcode('BLOBBASEFEE', 0x4a, 0, 1, 1),
  OpcodeInfo.unallocatedOpcode(0x4b),
  OpcodeInfo.unallocatedOpcode(0x4c),
  OpcodeInfo.unallocatedOpcode(0x4d),
  OpcodeInfo.unallocatedOpcode(0x4e),
  OpcodeInfo.unallocatedOpcode(0x4f),
  OpcodeInfo.validOpcode('POP', 0x50, 1, 0, 1),
  OpcodeInfo.validOpcode('MLOAD', 0x51, 1, 1, 1),
  OpcodeInfo.validOpcode('MSTORE', 0x52, 2, 0, 1),
  OpcodeInfo.validOpcode('MSTORE8', 0x53, 2, 0, 1),
  OpcodeInfo.validOpcode('SLOAD', 0x54, 1, 1, 1),
  OpcodeInfo.validOpcode('SSTORE', 0x55, 2, 0, 1),
  OpcodeInfo.invalidOpcode('JUMP', 0x56),
  OpcodeInfo.invalidOpcode('JUMPI', 0x57),
  OpcodeInfo.invalidOpcode('PC', 0x58),
  OpcodeInfo.validOpcode('MSIZE', 0x59, 0, 1, 1),
  OpcodeInfo.invalidOpcode('GAS', 0x5a),
  OpcodeInfo.validOpcode('NOOP', 0x5b, 0, 0, 1), // was JUMPDEST
  OpcodeInfo.validOpcode('TLOAD', 0x5c, 1, 1, 1),
  OpcodeInfo.validOpcode('TSTORE', 0x5d, 2, 0, 1),
  OpcodeInfo.validOpcode('MCOPY', 0x5e, 3, 0, 1),
  OpcodeInfo.validOpcode('PUSH0', 0x5f, 0, 1, 1),
  OpcodeInfo.validOpcode('PUSH1', 0x60, 0, 1, 2),
  OpcodeInfo.validOpcode('PUSH2', 0x61, 0, 1, 3),
  OpcodeInfo.validOpcode('PUSH3', 0x62, 0, 1, 4),
  OpcodeInfo.validOpcode('PUSH4', 0x63, 0, 1, 5),
  OpcodeInfo.validOpcode('PUSH5', 0x64, 0, 1, 6),
  OpcodeInfo.validOpcode('PUSH6', 0x65, 0, 1, 7),
  OpcodeInfo.validOpcode('PUSH7', 0x66, 0, 1, 8),
  OpcodeInfo.validOpcode('PUSH8', 0x67, 0, 1, 9),
  OpcodeInfo.validOpcode('PUSH9', 0x68, 0, 1, 10),
  OpcodeInfo.validOpcode('PUSH10', 0x69, 0, 1, 11),
  OpcodeInfo.validOpcode('PUSH11', 0x6a, 0, 1, 12),
  OpcodeInfo.validOpcode('PUSH12', 0x6b, 0, 1, 13),
  OpcodeInfo.validOpcode('PUSH13', 0x6c, 0, 1, 14),
  OpcodeInfo.validOpcode('PUSH14', 0x6d, 0, 1, 15),
  OpcodeInfo.validOpcode('PUSH15', 0x6e, 0, 1, 16),
  OpcodeInfo.validOpcode('PUSH16', 0x6f, 0, 1, 17),
  OpcodeInfo.validOpcode('PUSH17', 0x70, 0, 1, 18),
  OpcodeInfo.validOpcode('PUSH18', 0x71, 0, 1, 19),
  OpcodeInfo.validOpcode('PUSH19', 0x72, 0, 1, 20),
  OpcodeInfo.validOpcode('PUSH20', 0x73, 0, 1, 21),
  OpcodeInfo.validOpcode('PUSH21', 0x74, 0, 1, 22),
  OpcodeInfo.validOpcode('PUSH22', 0x75, 0, 1, 23),
  OpcodeInfo.validOpcode('PUSH23', 0x76, 0, 1, 24),
  OpcodeInfo.validOpcode('PUSH24', 0x77, 0, 1, 25),
  OpcodeInfo.validOpcode('PUSH25', 0x78, 0, 1, 26),
  OpcodeInfo.validOpcode('PUSH26', 0x79, 0, 1, 27),
  OpcodeInfo.validOpcode('PUSH27', 0x7a, 0, 1, 28),
  OpcodeInfo.validOpcode('PUSH28', 0x7b, 0, 1, 29),
  OpcodeInfo.validOpcode('PUSH29', 0x7c, 0, 1, 30),
  OpcodeInfo.validOpcode('PUSH30', 0x7d, 0, 1, 31),
  OpcodeInfo.validOpcode('PUSH31', 0x7e, 0, 1, 32),
  OpcodeInfo.validOpcode('PUSH32', 0x7f, 0, 1, 33),
  OpcodeInfo.validOpcode('DUP1', 0x80, 1, 2, 1),
  OpcodeInfo.validOpcode('DUP2', 0x81, 2, 3, 1),
  OpcodeInfo.validOpcode('DUP3', 0x82, 3, 4, 1),
  OpcodeInfo.validOpcode('DUP4', 0x83, 4, 5, 1),
  OpcodeInfo.validOpcode('DUP5', 0x84, 5, 6, 1),
  OpcodeInfo.validOpcode('DUP6', 0x85, 6, 7, 1),
  OpcodeInfo.validOpcode('DUP7', 0x86, 7, 8, 1),
  OpcodeInfo.validOpcode('DUP8', 0x87, 8, 9, 1),
  OpcodeInfo.validOpcode('DUP9', 0x88, 9, 10, 1),
  OpcodeInfo.validOpcode('DUP10', 0x89, 10, 11, 1),
  OpcodeInfo.validOpcode('DUP11', 0x8a, 11, 12, 1),
  OpcodeInfo.validOpcode('DUP12', 0x8b, 12, 13, 1),
  OpcodeInfo.validOpcode('DUP13', 0x8c, 13, 14, 1),
  OpcodeInfo.validOpcode('DUP14', 0x8d, 14, 15, 1),
  OpcodeInfo.validOpcode('DUP15', 0x8e, 15, 16, 1),
  OpcodeInfo.validOpcode('DUP16', 0x8f, 16, 17, 1),
  OpcodeInfo.validOpcode('SWAP1', 0x90, 2, 2, 1),
  OpcodeInfo.validOpcode('SWAP2', 0x91, 3, 3, 1),
  OpcodeInfo.validOpcode('SWAP3', 0x92, 4, 4, 1),
  OpcodeInfo.validOpcode('SWAP4', 0x93, 5, 5, 1),
  OpcodeInfo.validOpcode('SWAP5', 0x94, 6, 6, 1),
  OpcodeInfo.validOpcode('SWAP6', 0x95, 7, 7, 1),
  OpcodeInfo.validOpcode('SWAP7', 0x96, 8, 8, 1),
  OpcodeInfo.validOpcode('SWAP8', 0x97, 9, 9, 1),
  OpcodeInfo.validOpcode('SWAP9', 0x98, 10, 10, 1),
  OpcodeInfo.validOpcode('SWAP10', 0x99, 11, 11, 1),
  OpcodeInfo.validOpcode('SWAP11', 0x9a, 12, 12, 1),
  OpcodeInfo.validOpcode('SWAP12', 0x9b, 13, 13, 1),
  OpcodeInfo.validOpcode('SWAP13', 0x9c, 14, 14, 1),
  OpcodeInfo.validOpcode('SWAP14', 0x9d, 15, 15, 1),
  OpcodeInfo.validOpcode('SWAP15', 0x9e, 16, 16, 1),
  OpcodeInfo.validOpcode('SWAP16', 0x9f, 17, 17, 1),
  OpcodeInfo.validOpcode('LOG0', 0xa0, 2, 0, 1),
  OpcodeInfo.validOpcode('LOG1', 0xa1, 3, 0, 1),
  OpcodeInfo.validOpcode('LOG2', 0xa2, 4, 0, 1),
  OpcodeInfo.validOpcode('LOG3', 0xa3, 5, 0, 1),
  OpcodeInfo.validOpcode('LOG4', 0xa4, 6, 0, 1),
  OpcodeInfo.unallocatedOpcode(0xa5),
  OpcodeInfo.unallocatedOpcode(0xa6),
  OpcodeInfo.unallocatedOpcode(0xa7),
  OpcodeInfo.unallocatedOpcode(0xa8),
  OpcodeInfo.unallocatedOpcode(0xa9),
  OpcodeInfo.unallocatedOpcode(0xaa),
  OpcodeInfo.unallocatedOpcode(0xab),
  OpcodeInfo.unallocatedOpcode(0xac),
  OpcodeInfo.unallocatedOpcode(0xad),
  OpcodeInfo.unallocatedOpcode(0xae),
  OpcodeInfo.unallocatedOpcode(0xaf),
  OpcodeInfo.unallocatedOpcode(0xb0),
  OpcodeInfo.unallocatedOpcode(0xb1),
  OpcodeInfo.unallocatedOpcode(0xb2),
  OpcodeInfo.unallocatedOpcode(0xb3),
  OpcodeInfo.unallocatedOpcode(0xb4),
  OpcodeInfo.unallocatedOpcode(0xb5),
  OpcodeInfo.unallocatedOpcode(0xb6),
  OpcodeInfo.unallocatedOpcode(0xb7),
  OpcodeInfo.unallocatedOpcode(0xb8),
  OpcodeInfo.unallocatedOpcode(0xb9),
  OpcodeInfo.unallocatedOpcode(0xba),
  OpcodeInfo.unallocatedOpcode(0xbb),
  OpcodeInfo.unallocatedOpcode(0xbc),
  OpcodeInfo.unallocatedOpcode(0xbd),
  OpcodeInfo.unallocatedOpcode(0xbe),
  OpcodeInfo.unallocatedOpcode(0xbf),
  OpcodeInfo.unallocatedOpcode(0xc0),
  OpcodeInfo.unallocatedOpcode(0xc1),
  OpcodeInfo.unallocatedOpcode(0xc2),
  OpcodeInfo.unallocatedOpcode(0xc3),
  OpcodeInfo.unallocatedOpcode(0xc4),
  OpcodeInfo.unallocatedOpcode(0xc5),
  OpcodeInfo.unallocatedOpcode(0xc6),
  OpcodeInfo.unallocatedOpcode(0xc7),
  OpcodeInfo.unallocatedOpcode(0xc8),
  OpcodeInfo.unallocatedOpcode(0xc9),
  OpcodeInfo.unallocatedOpcode(0xca),
  OpcodeInfo.unallocatedOpcode(0xcb),
  OpcodeInfo.unallocatedOpcode(0xcc),
  OpcodeInfo.unallocatedOpcode(0xcd),
  OpcodeInfo.unallocatedOpcode(0xce),
  OpcodeInfo.unallocatedOpcode(0xcf),
  OpcodeInfo.validOpcode('DATALOAD', 0xd0, 1, 1, 1),
  OpcodeInfo.validOpcode('DATALOADN', 0xd1, 0, 1, 3),
  OpcodeInfo.validOpcode('DATASIZE', 0xd2, 0, 1, 1),
  OpcodeInfo.validOpcode('DATACOPY', 0xd3, 3, 0, 1),
  OpcodeInfo.unallocatedOpcode(0xd4),
  OpcodeInfo.unallocatedOpcode(0xd5),
  OpcodeInfo.unallocatedOpcode(0xd6),
  OpcodeInfo.unallocatedOpcode(0xd7),
  OpcodeInfo.unallocatedOpcode(0xd8),
  OpcodeInfo.unallocatedOpcode(0xd9),
  OpcodeInfo.unallocatedOpcode(0xda),
  OpcodeInfo.unallocatedOpcode(0xdb),
  OpcodeInfo.unallocatedOpcode(0xdc),
  OpcodeInfo.unallocatedOpcode(0xdd),
  OpcodeInfo.unallocatedOpcode(0xde),
  OpcodeInfo.unallocatedOpcode(0xdf),
  OpcodeInfo.terminalOpcode('RJUMP', 0xe0, 0, 0, 3),
  OpcodeInfo.validOpcode('RJUMPI', 0xe1, 1, 0, 3),
  OpcodeInfo.validOpcode('RJUMPV', 0xe2, 1, 0, 2),
  OpcodeInfo.validOpcode('CALLF', 0xe3, 0, 0, 3),
  OpcodeInfo.terminalOpcode('RETF', 0xe4, 0, 0, 1),
  OpcodeInfo.terminalOpcode('JUMPF', 0xe5, 0, 0, 3),
  OpcodeInfo.validOpcode('DUPN', 0xe6, 0, 1, 2),
  OpcodeInfo.validOpcode('SWAPN', 0xe7, 0, 0, 2),
  OpcodeInfo.validOpcode('EXCHANGE', 0xe8, 0, 0, 2),
  OpcodeInfo.unallocatedOpcode(0xe9),
  OpcodeInfo.unallocatedOpcode(0xea),
  OpcodeInfo.unallocatedOpcode(0xeb),
  OpcodeInfo.validOpcode('EOFCREATE', 0xec, 4, 1, 2),
  OpcodeInfo.unallocatedOpcode(0xed),
  OpcodeInfo.terminalOpcode('RETURNCONTRACT', 0xee, 2, 1, 2),
  OpcodeInfo.unallocatedOpcode(0xef),
  OpcodeInfo.invalidOpcode('CREATE', 0xf0),
  OpcodeInfo.invalidOpcode('CALL', 0xf1),
  OpcodeInfo.invalidOpcode('CALLCODE', 0xf2),
  OpcodeInfo.terminalOpcode('RETURN', 0xf3, 2, 0, 1),
  OpcodeInfo.invalidOpcode('DELEGATECALL', 0xf4),
  OpcodeInfo.invalidOpcode('CREATE2', 0xf5),
  OpcodeInfo.unallocatedOpcode(0xf6),
  OpcodeInfo.validOpcode('RETURNDATALOAD', 0xf7, 1, 1, 1),
  OpcodeInfo.validOpcode('EXTCALL', 0xf8, 4, 1, 1),
  OpcodeInfo.validOpcode('EXTDELEGATECALL', 0xf9, 3, 1, 1),
  OpcodeInfo.invalidOpcode('STATICCALL', 0xfa),
  OpcodeInfo.validOpcode('EXTSTATICCALL', 0xfb, 3, 1, 1),
  OpcodeInfo.unallocatedOpcode(0xfc),
  OpcodeInfo.terminalOpcode('REVERT', 0xfd, 2, 0, 1),
  OpcodeInfo.terminalOpcode('INVALID', 0xfe, 0, 0, 1),
  OpcodeInfo.invalidOpcode('SELFDESTRUCT', 0xff),
]

console.log(JSON.stringify(stackDelta))


*/
