// Generated using a script, which can be found in ./evm/scripts/stackDeltaGenerator.ts

export const stackDelta: {
  [key: number]: {
    inputs: number // Number of inputs to this operation
    outputs: number // Number of outputs after this operation
    name: string // Name of the opcode
    intermediates: number // Intermediate bytes (such as 2 intermediates after a PUSH2)
    terminating?: boolean // Marks the opcode as terminating. This opcode will exit the current CALL frame. (Such as STOP/RETURN)
  }
} = {
  0: {
    inputs: 0,
    outputs: 0,
    name: 'STOP',
    intermediates: 0,
    terminating: true,
  },
  1: { inputs: 2, outputs: 1, name: 'ADD', intermediates: 0 },
  2: { inputs: 2, outputs: 1, name: 'MUL', intermediates: 0 },
  3: { inputs: 2, outputs: 1, name: 'SUB', intermediates: 0 },
  4: { inputs: 2, outputs: 1, name: 'DIV', intermediates: 0 },
  5: { inputs: 2, outputs: 1, name: 'SDIV', intermediates: 0 },
  6: { inputs: 2, outputs: 1, name: 'MOD', intermediates: 0 },
  7: { inputs: 2, outputs: 1, name: 'SMOD', intermediates: 0 },
  8: { inputs: 3, outputs: 1, name: 'ADDMOD', intermediates: 0 },
  9: { inputs: 3, outputs: 1, name: 'MULMOD', intermediates: 0 },
  10: { inputs: 2, outputs: 1, name: 'EXP', intermediates: 0 },
  11: { inputs: 2, outputs: 1, name: 'SIGNEXTEND', intermediates: 0 },
  16: { inputs: 2, outputs: 1, name: 'LT', intermediates: 0 },
  17: { inputs: 2, outputs: 1, name: 'GT', intermediates: 0 },
  18: { inputs: 2, outputs: 1, name: 'SLT', intermediates: 0 },
  19: { inputs: 2, outputs: 1, name: 'SGT', intermediates: 0 },
  20: { inputs: 2, outputs: 1, name: 'EQ', intermediates: 0 },
  21: { inputs: 1, outputs: 1, name: 'ISZERO', intermediates: 0 },
  22: { inputs: 2, outputs: 1, name: 'AND', intermediates: 0 },
  23: { inputs: 2, outputs: 1, name: 'OR', intermediates: 0 },
  24: { inputs: 2, outputs: 1, name: 'XOR', intermediates: 0 },
  25: { inputs: 1, outputs: 1, name: 'NOT', intermediates: 0 },
  26: { inputs: 2, outputs: 1, name: 'BYTE', intermediates: 0 },
  27: { inputs: 2, outputs: 1, name: 'SHL', intermediates: 0 },
  28: { inputs: 2, outputs: 1, name: 'SHR', intermediates: 0 },
  29: { inputs: 2, outputs: 1, name: 'SAR', intermediates: 0 },
  32: { inputs: 2, outputs: 1, name: 'SHA3', intermediates: 0 },
  48: { inputs: 0, outputs: 1, name: 'ADDRESS', intermediates: 0 },
  49: { inputs: 1, outputs: 1, name: 'BALANCE', intermediates: 0 },
  50: { inputs: 0, outputs: 1, name: 'ORIGIN', intermediates: 0 },
  51: { inputs: 0, outputs: 1, name: 'CALLER', intermediates: 0 },
  52: { inputs: 0, outputs: 1, name: 'CALLVALUE', intermediates: 0 },
  53: { inputs: 1, outputs: 1, name: 'CALLDATALOAD', intermediates: 0 },
  54: { inputs: 0, outputs: 1, name: 'CALLDATASIZE', intermediates: 0 },
  55: { inputs: 3, outputs: 0, name: 'CALLDATACOPY', intermediates: 0 },
  58: { inputs: 0, outputs: 1, name: 'GASPRICE', intermediates: 0 },
  61: { inputs: 0, outputs: 1, name: 'RETURNDATASIZE', intermediates: 0 },
  62: { inputs: 3, outputs: 0, name: 'RETURNDATACOPY', intermediates: 0 },
  64: { inputs: 1, outputs: 1, name: 'BLOCKHASH', intermediates: 0 },
  65: { inputs: 0, outputs: 1, name: 'COINBASE', intermediates: 0 },
  66: { inputs: 0, outputs: 1, name: 'TIMESTAMP', intermediates: 0 },
  67: { inputs: 0, outputs: 1, name: 'NUMBER', intermediates: 0 },
  68: { inputs: 0, outputs: 1, name: 'PREVRANDAO', intermediates: 0 },
  69: { inputs: 0, outputs: 1, name: 'GASLIMIT', intermediates: 0 },
  70: { inputs: 0, outputs: 1, name: 'CHAINID', intermediates: 0 },
  71: { inputs: 0, outputs: 1, name: 'SELFBALANCE', intermediates: 0 },
  72: { inputs: 0, outputs: 1, name: 'BASEFEE', intermediates: 0 },
  73: { inputs: 1, outputs: 1, name: 'BLOBAHASH', intermediates: 0 },
  74: { inputs: 0, outputs: 1, name: 'BLOBBASEFEE', intermediates: 0 },
  80: { inputs: 1, outputs: 0, name: 'POP', intermediates: 0 },
  81: { inputs: 1, outputs: 1, name: 'MLOAD', intermediates: 0 },
  82: { inputs: 2, outputs: 0, name: 'MSTORE', intermediates: 0 },
  83: { inputs: 2, outputs: 0, name: 'MSTORE8', intermediates: 0 },
  84: { inputs: 1, outputs: 1, name: 'SLOAD', intermediates: 0 },
  85: { inputs: 2, outputs: 0, name: 'SSTORE', intermediates: 0 },
  89: { inputs: 0, outputs: 1, name: 'MSIZE', intermediates: 0 },
  91: { inputs: 0, outputs: 0, name: 'NOOP', intermediates: 0 },
  92: { inputs: 1, outputs: 1, name: 'TLOAD', intermediates: 0 },
  93: { inputs: 2, outputs: 0, name: 'TSTORE', intermediates: 0 },
  94: { inputs: 3, outputs: 0, name: 'MCOPY', intermediates: 0 },
  95: { inputs: 0, outputs: 1, name: 'PUSH0', intermediates: 0 },
  96: { inputs: 0, outputs: 1, name: 'PUSH1', intermediates: 1 },
  97: { inputs: 0, outputs: 1, name: 'PUSH2', intermediates: 2 },
  98: { inputs: 0, outputs: 1, name: 'PUSH3', intermediates: 3 },
  99: { inputs: 0, outputs: 1, name: 'PUSH4', intermediates: 4 },
  100: { inputs: 0, outputs: 1, name: 'PUSH5', intermediates: 5 },
  101: { inputs: 0, outputs: 1, name: 'PUSH6', intermediates: 6 },
  102: { inputs: 0, outputs: 1, name: 'PUSH7', intermediates: 7 },
  103: { inputs: 0, outputs: 1, name: 'PUSH8', intermediates: 8 },
  104: { inputs: 0, outputs: 1, name: 'PUSH9', intermediates: 9 },
  105: { inputs: 0, outputs: 1, name: 'PUSH10', intermediates: 10 },
  106: { inputs: 0, outputs: 1, name: 'PUSH11', intermediates: 11 },
  107: { inputs: 0, outputs: 1, name: 'PUSH12', intermediates: 12 },
  108: { inputs: 0, outputs: 1, name: 'PUSH13', intermediates: 13 },
  109: { inputs: 0, outputs: 1, name: 'PUSH14', intermediates: 14 },
  110: { inputs: 0, outputs: 1, name: 'PUSH15', intermediates: 15 },
  111: { inputs: 0, outputs: 1, name: 'PUSH16', intermediates: 16 },
  112: { inputs: 0, outputs: 1, name: 'PUSH17', intermediates: 17 },
  113: { inputs: 0, outputs: 1, name: 'PUSH18', intermediates: 18 },
  114: { inputs: 0, outputs: 1, name: 'PUSH19', intermediates: 19 },
  115: { inputs: 0, outputs: 1, name: 'PUSH20', intermediates: 20 },
  116: { inputs: 0, outputs: 1, name: 'PUSH21', intermediates: 21 },
  117: { inputs: 0, outputs: 1, name: 'PUSH22', intermediates: 22 },
  118: { inputs: 0, outputs: 1, name: 'PUSH23', intermediates: 23 },
  119: { inputs: 0, outputs: 1, name: 'PUSH24', intermediates: 24 },
  120: { inputs: 0, outputs: 1, name: 'PUSH25', intermediates: 25 },
  121: { inputs: 0, outputs: 1, name: 'PUSH26', intermediates: 26 },
  122: { inputs: 0, outputs: 1, name: 'PUSH27', intermediates: 27 },
  123: { inputs: 0, outputs: 1, name: 'PUSH28', intermediates: 28 },
  124: { inputs: 0, outputs: 1, name: 'PUSH29', intermediates: 29 },
  125: { inputs: 0, outputs: 1, name: 'PUSH30', intermediates: 30 },
  126: { inputs: 0, outputs: 1, name: 'PUSH31', intermediates: 31 },
  127: { inputs: 0, outputs: 1, name: 'PUSH32', intermediates: 32 },
  128: { inputs: 1, outputs: 2, name: 'DUP1', intermediates: 0 },
  129: { inputs: 2, outputs: 3, name: 'DUP2', intermediates: 0 },
  130: { inputs: 3, outputs: 4, name: 'DUP3', intermediates: 0 },
  131: { inputs: 4, outputs: 5, name: 'DUP4', intermediates: 0 },
  132: { inputs: 5, outputs: 6, name: 'DUP5', intermediates: 0 },
  133: { inputs: 6, outputs: 7, name: 'DUP6', intermediates: 0 },
  134: { inputs: 7, outputs: 8, name: 'DUP7', intermediates: 0 },
  135: { inputs: 8, outputs: 9, name: 'DUP8', intermediates: 0 },
  136: { inputs: 9, outputs: 10, name: 'DUP9', intermediates: 0 },
  137: { inputs: 10, outputs: 11, name: 'DUP10', intermediates: 0 },
  138: { inputs: 11, outputs: 12, name: 'DUP11', intermediates: 0 },
  139: { inputs: 12, outputs: 13, name: 'DUP12', intermediates: 0 },
  140: { inputs: 13, outputs: 14, name: 'DUP13', intermediates: 0 },
  141: { inputs: 14, outputs: 15, name: 'DUP14', intermediates: 0 },
  142: { inputs: 15, outputs: 16, name: 'DUP15', intermediates: 0 },
  143: { inputs: 16, outputs: 17, name: 'DUP16', intermediates: 0 },
  144: { inputs: 2, outputs: 2, name: 'SWAP1', intermediates: 0 },
  145: { inputs: 3, outputs: 3, name: 'SWAP2', intermediates: 0 },
  146: { inputs: 4, outputs: 4, name: 'SWAP3', intermediates: 0 },
  147: { inputs: 5, outputs: 5, name: 'SWAP4', intermediates: 0 },
  148: { inputs: 6, outputs: 6, name: 'SWAP5', intermediates: 0 },
  149: { inputs: 7, outputs: 7, name: 'SWAP6', intermediates: 0 },
  150: { inputs: 8, outputs: 8, name: 'SWAP7', intermediates: 0 },
  151: { inputs: 9, outputs: 9, name: 'SWAP8', intermediates: 0 },
  152: { inputs: 10, outputs: 10, name: 'SWAP9', intermediates: 0 },
  153: { inputs: 11, outputs: 11, name: 'SWAP10', intermediates: 0 },
  154: { inputs: 12, outputs: 12, name: 'SWAP11', intermediates: 0 },
  155: { inputs: 13, outputs: 13, name: 'SWAP12', intermediates: 0 },
  156: { inputs: 14, outputs: 14, name: 'SWAP13', intermediates: 0 },
  157: { inputs: 15, outputs: 15, name: 'SWAP14', intermediates: 0 },
  158: { inputs: 16, outputs: 16, name: 'SWAP15', intermediates: 0 },
  159: { inputs: 17, outputs: 17, name: 'SWAP16', intermediates: 0 },
  160: { inputs: 2, outputs: 0, name: 'LOG0', intermediates: 0 },
  161: { inputs: 3, outputs: 0, name: 'LOG1', intermediates: 0 },
  162: { inputs: 4, outputs: 0, name: 'LOG2', intermediates: 0 },
  163: { inputs: 5, outputs: 0, name: 'LOG3', intermediates: 0 },
  164: { inputs: 6, outputs: 0, name: 'LOG4', intermediates: 0 },
  208: { inputs: 1, outputs: 1, name: 'DATALOAD', intermediates: 0 },
  209: { inputs: 0, outputs: 1, name: 'DATALOADN', intermediates: 2 },
  210: { inputs: 0, outputs: 1, name: 'DATASIZE', intermediates: 0 },
  211: { inputs: 3, outputs: 0, name: 'DATACOPY', intermediates: 0 },
  224: { inputs: 0, outputs: 0, name: 'RJUMP', intermediates: 2 },
  225: { inputs: 1, outputs: 0, name: 'RJUMPI', intermediates: 2 },
  // NOTE: for RJUMPV the intermediate byte is set to 0, this has to do with the validation algorithm specifics
  // This has to do with the dynamic intermediate size of RJUMPV, which depends upon the table size byte right after RJUMPV
  226: { inputs: 1, outputs: 0, name: 'RJUMPV', intermediates: 0 },
  // CALLF special case for stack validation algorithm: the inputs and outputs MUST stay 0
  // (this is currently the case also in EVM)
  227: { inputs: 0, outputs: 0, name: 'CALLF', intermediates: 2 },
  228: {
    inputs: 0,
    outputs: 0,
    name: 'RETF',
    intermediates: 0,
    terminating: true,
  },
  229: {
    inputs: 0,
    outputs: 0,
    name: 'JUMPF',
    intermediates: 2,
    terminating: true,
  },
  230: { inputs: 0, outputs: 1, name: 'DUPN', intermediates: 1 },
  231: { inputs: 0, outputs: 0, name: 'SWAPN', intermediates: 1 },
  232: { inputs: 0, outputs: 0, name: 'EXCHANGE', intermediates: 1 },
  236: { inputs: 4, outputs: 1, name: 'EOFCREATE', intermediates: 1 },
  238: {
    inputs: 2,
    outputs: 0,
    name: 'RETURNCONTRACT',
    intermediates: 1,
    terminating: true,
  },
  243: {
    inputs: 2,
    outputs: 0,
    name: 'RETURN',
    intermediates: 0,
    terminating: true,
  },
  247: { inputs: 1, outputs: 1, name: 'RETURNDATALOAD', intermediates: 0 },
  248: { inputs: 4, outputs: 1, name: 'EXTCALL', intermediates: 0 },
  249: { inputs: 3, outputs: 1, name: 'EXTDELEGATECALL', intermediates: 0 },
  251: { inputs: 3, outputs: 1, name: 'EXTSTATICCALL', intermediates: 0 },
  253: {
    inputs: 2,
    outputs: 0,
    name: 'REVERT',
    intermediates: 0,
    terminating: true,
  },
  254: {
    inputs: 0,
    outputs: 0,
    name: 'INVALID',
    intermediates: 0,
    terminating: true,
  },
}
