#!/bin/bash

# immediately exits when a command fails
# set -e

# Print commands as they are ran
# set -o xtrace

echo -e "\033[0;32mApplying patches to the code...\033[0m"

for patch in `find ./scripts/*.patch`; do
    echo $patch
    patch -p0 -N < $patch
done

# Cleaning files generated by `patch` command
git clean -f *.rej
