name: Blockchain
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
      run-coverage:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'
      run-coverage:
        required: false
        type: boolean
        default: true

env:
  cwd: ${{github.workspace}}/packages/blockchain
  RUN_COVERAGE: ${{ inputs.run-coverage }}

defaults:
  run:
    working-directory: packages/blockchain

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-blockchain
  cancel-in-progress: true

jobs:
  test-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-ethereumjs
        with:
          dep-cache-key: ${{ inputs.dep-cache-key }}

      - run: |
          if [ "$RUN_COVERAGE" = "false" ]; then
            npm run test:node
          else
            npm run coverage
          fi
      - if: env.RUN_COVERAGE != 'false'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: blockchain
