name: Client
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'

env:
  cwd: ${{github.workspace}}/packages/client

defaults:
  run:
    working-directory: packages/client

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-client
  cancel-in-progress: true

jobs:
  test-client:
    if: contains(join(github.event.pull_request.labels.*.name, ' '), 'test client')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ethereumjs
        with:
          dep-cache-key: ${{ inputs.dep-cache-key }}

      - run: npm run coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: client

      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd ${{github.workspace}}/packages/client && npm run test:integration

  test-client-cli:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-ethereumjs
        with:
          dep-cache-key: ${{ inputs.dep-cache-key }}

      - run: cd ${{github.workspace}}/packages/client && npx vitest run test/cli/cli
