name: EVM
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
      submodule-cache-key:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'
      submodule-cache-key:
        required: false
        default: 'none'

env:
  cwd: ${{github.workspace}}/packages/evm

defaults:
  run:
    working-directory: packages/evm

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-evm
  cancel-in-progress: true

jobs:
  test-evm:
    runs-on: ubuntu-latest
    steps:
      # We clone the repo and submodules if triggered from work-flow dispatch
      - if: inputs.submodule-cache-key == 'none'
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # We restore the code/deps from cache if triggered from workflow_call (i.e. have valid cache key)
      - if: inputs.dep-cache-key != 'none' 
        uses: actions/cache/restore@v4
        id: dep-cache
        with:
          path: ${{github.workspace}}
          key: ${{ inputs.dep-cache-key }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies (if not restored from cache)
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci     
        working-directory: ${{ github.workspace }}
           
      - if: inputs.submodule-cache-key != 'none'
        uses: actions/cache/restore@v4
        name: Initialize ethereum-tests
        id: submodules-cache
        with:
          path: ${{github.workspace}}/packages/ethereum-tests
          key: ${{ inputs.submodule-cache-key }}
          fail-on-cache-miss: true

      - run: npm run coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.cwd }}/coverage/lcov.info
          flags: evm