participants:
  - el_type: geth
    cl_type: lighthouse
    count: 1
  - el_type: ethereumjs
    # el_image: ethereumjs:local
    cl_type: lodestar
    count: 1
additional_services:
  - assertoor
assertoor_params:
  run_stability_check: false
  run_block_proposal_check: false
  tests:
    - https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/block-proposal-check.yaml
    - https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/all-opcodes-test.yaml