name: Typecheck (tsc)
on:
  workflow_call:
    inputs:
      dep-cache-key:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      dep-cache-key:
        required: false
        default: 'none'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-typecheck
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-ethereumjs
        with:
          dep-cache-key: ${{ inputs.dep-cache-key }}

      - run: npm run tsc --workspaces
        working-directory: ${{ github.workspace }}
